postMerge :
  preRun: 
    command:
      - yarn install
      
  
  subModules:          #Not to be changed
      
        
      - name:  framesync
        path : "./packages/framesync"
        pattern: 
          - "./src/_tests/test.ts"
        
        framework : jest
        preRun:
          command:
            - node --version
          
        postRun:
            command:
              - node --version 
        
      - name:  projection
        path : "./packages/projection"
        pattern: 
          - "./src/__tests__/*test.ts"
        
        framework : jest
        preRun:
          command:
            - node --version
      
          
        postRun:
            command:
              - node --version 
      
      
      - name:  style-value-types
        path : "./packages/style-value-types"
        pattern: 
          - "./src/_tests/*.ts"
        
        framework : jest
        preRun:
          command:
            - node --version
        
preMerge : 
  preRun: 
    command:
      - yarn install
      
  
  subModules:          #Not to be changed
     
      - name:  framesync
        path : "./packages/framesync"
        pattern: 
          - "./src/_tests/test.ts"
        
        framework : jest
        preRun:
          command:
            - node --version
          
        postRun:
            command:
              - node --version 
        
      - name:  projection
        path : "./packages/projection"
        pattern: 
          - "./src/__tests__/*test.ts"
        
        framework : jest
        preRun:
          command:
            - node --version
      
          
        postRun:
            command:
              - node --version 
      
      
      - name:  style-value-types
        path : "./packages/style-value-types"
        pattern: 
          - "./src/_tests/*.ts"
        
        framework : jest
        preRun:
          command:
            - node --version
            
version : 2.0.2
nodeVersion : 17.3.1

